version: '3.8'

services:
  app:
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_LEVEL=warning
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_production_password}
      POSTGRES_SHARED_PRELOAD_LIBRARIES: pg_stat_statements
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/postgres/backup:/backup
    command: postgres -c log_statement=all -c log_destination=stderr -c logging_collector=on
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  redis:
    restart: always
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru --requirepass ${REDIS_PASSWORD:-}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    restart: always
    volumes:
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf

  # Production monitoring
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - pg_card_network

volumes:
  db_data:
    driver: local